version: '3'
services:
  mongodb:
    image: mongo:4.4.4
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    command: --wiredTigerCacheSizeGB 1.5